[package]
name = "cfg-manager"
version = "1.0.0"
edition = "2024"

[dependencies]
toml = "1.1.2"
windows-registry = "0.6.1"
anyhow = "1.0.102"
log = "0.4"
env_logger = "0.11.10"
serde = { version = "1.0.228", features = ["derive"] }
windows = { version = "0.62.2", features = ["Win32_UI_WindowsAndMessaging"] }